Repository crane93/Issue-Maker, pull requests merged in 2019-05, with the labels that each got.

#9 gradle branch
  demo/.classpath
  demo/.gitignore
  demo/.project
  demo/.settings/org.eclipse.buildship.core.prefs
  demo/bin/main/demo/Application.class
  demo/bin/main/demo/HelloController.class
  demo/bin/main/webapp/WEB-INF/jsp/hello.jsp
  demo/build.gradle
  demo/src/main/java/Application.java
  demo/src/main/java/demo/App.java
  demo/src/main/java/demo/Application.java
  demo/src/main/java/demo/HelloController.java
  demo/src/main/java/webapp/WEB-INF/jsp/hello.jsp
  demo/src/test/java/demo/AppTest.java
Labels: LGTM!, Merge OK

#10 Spring boot
  demo/.gitignore
  demo/build.gradle
  demo/gradle/wrapper/gradle-wrapper.jar
  demo/src/main/java/hello/Application.java
  demo/src/main/java/hello/HelloController.java
Labels: LGTM!, Merge OK

#12 View using JSP on Spring Boot
  demo/.gitignore
  demo/build.gradle
  demo/src/main/java/demo/App.java
  demo/src/main/java/hello/HelloController.java
  demo/src/main/resources/application.properties
  demo/src/main/webapp/WEB-INF/jsp/hello.jsp
Labels: Merge OK

#14 Gradle wapper를 사용가능하게 하기
  demo/gradle/wrapper/gradle-wrapper.jar
  demo/gradle/wrapper/gradle-wrapper.properties
  demo/src/test/java/demo/AppTest.java
Labels: LGTM!
